<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class AccessRuleCurrentStatusCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DAILY_LIMIT_EXCEEDED = 'DailyLimitExceeded';
    const C_DAILY_SOFT_LIMIT_EXCEEDED = 'DailySoftLimitExceeded';
    const C_HOURLY_LIMIT_EXCEEDED = 'HourlyLimitExceeded';
    const C_HOURLY_SOFT_LIMIT_EXCEEDED = 'HourlySoftLimitExceeded';
    const C_NOT_SET = 'NotSet';
    const C_PERIODIC_LIMIT_EXCEEDED = 'PeriodicLimitExceeded';
    const C_PERIODIC_SOFT_LIMIT_EXCEEDED = 'PeriodicSoftLimitExceeded';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
