<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class BidActionCodeType extends Enum 
{
    const C_ABSENTEE = 'Absentee';
    const C_ACCEPT = 'Accept';
    const C_AUTO_CANCEL = 'AutoCancel';
    const C_AUTO_RETRACTION = 'AutoRetraction';
    const C_BID = 'Bid';
    const C_BUY_IT_NOW = 'BuyItNow';
    const C_CANCELLED = 'Cancelled';
    const C_COUNTER = 'Counter';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DECLINE = 'Decline';
    const C_OFFER = 'Offer';
    const C_PURCHASE = 'Purchase';
    const C_RETRACTION = 'Retraction';
    const C_UNKNOWN = 'Unknown';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
