<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class BuyerPaymentInstrumentCodeType extends Enum 
{
    const C_BANK_DIRECT_DEBIT = 'BankDirectDebit';
    const C_BML = 'BML';
    const C_CREDIT_CARD = 'CreditCard';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_ELV = 'ELV';
    const C_GIROPAY = 'GIROPAY';
    const C_LOCAL_PAYMENT_AMEX = 'LocalPaymentAMEX';
    const C_LOCAL_PAYMENT_CREDIT_CARD_OTHER = 'LocalPaymentCreditCardOther';
    const C_LOCAL_PAYMENT_DINERSCLUB = 'LocalPaymentDinersclub';
    const C_LOCAL_PAYMENT_DISCOVER = 'LocalPaymentDiscover';
    const C_LOCAL_PAYMENT_ELV = 'LocalPaymentELV';
    const C_LOCAL_PAYMENT_JCB = 'LocalPaymentJCB';
    const C_LOCAL_PAYMENT_MASTER_CARD = 'LocalPaymentMasterCard';
    const C_LOCAL_PAYMENT_SOLO = 'LocalPaymentSOLO';
    const C_LOCAL_PAYMENT_SWITCH = 'LocalPaymentSWITCH';
    const C_LOCAL_PAYMENT_VISA = 'LocalPaymentVISA';
    const C_NONE = 'None';
    const C_PAY_PAL = 'PayPal';
    const C_PAY_UPON_INVOICE = 'PayUponInvoice';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
