<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class CheckoutStatusCodeType extends Enum 
{
    const C_BUYER_REQUESTS_TOTAL = 'BuyerRequestsTotal';
    const C_CHECKOUT_COMPLETE = 'CheckoutComplete';
    const C_CHECKOUT_INCOMPLETE = 'CheckoutIncomplete';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_SELLER_RESPONDED = 'SellerResponded';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
