<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DetailLevelCodeType extends Enum 
{
    const C_ITEM_RETURN_ATTRIBUTES = 'ItemReturnAttributes';
    const C_ITEM_RETURN_CATEGORIES = 'ItemReturnCategories';
    const C_ITEM_RETURN_DESCRIPTION = 'ItemReturnDescription';
    const C_RETURN_ALL = 'ReturnAll';
    const C_RETURN_HEADERS = 'ReturnHeaders';
    const C_RETURN_MESSAGES = 'ReturnMessages';
    const C_RETURN_SUMMARY = 'ReturnSummary';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
