<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeStatusCodeType extends Enum 
{
    const C_CLAIM_APPROVED = 'ClaimApproved';
    const C_CLAIM_CLOSED = 'ClaimClosed';
    const C_CLAIM_DENIED = 'ClaimDenied';
    const C_CLAIM_IN_PROCESS = 'ClaimInProcess';
    const C_CLAIM_OPENED = 'ClaimOpened';
    const C_CLAIM_PAID = 'ClaimPaid';
    const C_CLAIM_RESOLVED = 'ClaimResolved';
    const C_CLAIM_SUBMITTED = 'ClaimSubmitted';
    const C_CLOSED = 'Closed';
    const C_CLOSED_FVF_CREDIT_NO_STRIKE = 'ClosedFVFCreditNoStrike';
    const C_CLOSED_FVF_CREDIT_STRIKE = 'ClosedFVFCreditStrike';
    const C_CLOSED_NO_FVF_CREDIT_NO_STRIKE = 'ClosedNoFVFCreditNoStrike';
    const C_CLOSED_NO_FVF_CREDIT_STRIKE = 'ClosedNoFVFCreditStrike';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_FVF_CREDIT_REVERSED_AFTER_CLOSING = 'FVFCreditReversedAfterClosing';
    const C_NO_DOCUMENTATION = 'NoDocumentation';
    const C_STRIKE_APPEALED_AFTER_CLOSING = 'StrikeAppealedAfterClosing';
    const C_STRIKE_APPEALED_AND_FVF_CREDIT_REVERSED = 'StrikeAppealedAndFVFCreditReversed';
    const C_UNPAID_ITEM_OPENED = 'UnpaidItemOpened';
    const C_WAITING_FOR_BUYER_RESPONSE = 'WaitingForBuyerResponse';
    const C_WAITING_FOR_SELLER_RESPONSE = 'WaitingForSellerResponse';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
