<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeFilterTypeCodeType extends Enum 
{
    const C_ALL_INVOLVED_CLOSED_DISPUTES = 'AllInvolvedClosedDisputes';
    const C_ALL_INVOLVED_DISPUTES = 'AllInvolvedDisputes';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DISPUTES_AWAITING_MY_RESPONSE = 'DisputesAwaitingMyResponse';
    const C_DISPUTES_AWAITING_OTHER_PARTY_RESPONSE = 'DisputesAwaitingOtherPartyResponse';
    const C_ELIGIBLE_FOR_CREDIT = 'EligibleForCredit';
    const C_ITEM_NOT_RECEIVED_DISPUTES = 'ItemNotReceivedDisputes';
    const C_UNPAID_ITEM_DISPUTES = 'UnpaidItemDisputes';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
