<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeSortTypeCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DISPUTE_CREATED_TIME_ASCENDING = 'DisputeCreatedTimeAscending';
    const C_DISPUTE_CREATED_TIME_DESCENDING = 'DisputeCreatedTimeDescending';
    const C_DISPUTE_CREDIT_ELIGIBILITY_ASCENDING = 'DisputeCreditEligibilityAscending';
    const C_DISPUTE_CREDIT_ELIGIBILITY_DESCENDING = 'DisputeCreditEligibilityDescending';
    const C_DISPUTE_STATUS_ASCENDING = 'DisputeStatusAscending';
    const C_DISPUTE_STATUS_DESCENDING = 'DisputeStatusDescending';
    const C_NONE = 'None';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
