<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeReasonCodeType extends Enum 
{
    const C_BUYER_HAS_NOT_PAID = 'BuyerHasNotPaid';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_ITEM_NOT_RECEIVED = 'ItemNotReceived';
    const C_NO_REFUND = 'NoRefund';
    const C_RETURN_POLICY_UNPAID_ITEM = 'ReturnPolicyUnpaidItem';
    const C_SIGNIFICANTLY_NOT_AS_DESCRIBED = 'SignificantlyNotAsDescribed';
    const C_TRANSACTION_MUTUALLY_CANCELED = 'TransactionMutuallyCanceled';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
