<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class EBaySubscriptionTypeCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_EBAY_STORE_ANCHOR = 'EBayStoreAnchor';
    const C_EBAY_STORE_BASIC = 'EBayStoreBasic';
    const C_EBAY_STORE_FEATURED = 'EBayStoreFeatured';
    const C_FILE_EXCHANGE = 'FileExchange';
    const C_LOCAL_MARKET_PREMIUM = 'LocalMarketPremium';
    const C_LOCAL_MARKET_REGULAR = 'LocalMarketRegular';
    const C_LOCAL_MARKET_SPECIALTY = 'LocalMarketSpecialty';
    const C_SELLER_REPORTS_PLUS = 'SellerReportsPlus';
    const C_SELLING_MANAGER = 'SellingManager';
    const C_SELLING_MANAGER_PRO = 'SellingManagerPro';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
