<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class EndReasonCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_INCORRECT = 'Incorrect';
    const C_LOST_OR_BROKEN = 'LostOrBroken';
    const C_NOT_AVAILABLE = 'NotAvailable';
    const C_OTHER_LISTING_ERROR = 'OtherListingError';
    const C_PRODUCT_DELETED = 'ProductDeleted';
    const C_SELL_TO_HIGH_BIDDER = 'SellToHighBidder';
    const C_SOLD = 'Sold';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
