<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class FeedbackRatingStarCodeType extends Enum 
{
    const C_BLUE = 'Blue';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_GREEN = 'Green';
    const C_GREEN_SHOOTING = 'GreenShooting';
    const C_NONE = 'None';
    const C_PURPLE = 'Purple';
    const C_PURPLE_SHOOTING = 'PurpleShooting';
    const C_RED = 'Red';
    const C_RED_SHOOTING = 'RedShooting';
    const C_SILVER_SHOOTING = 'SilverShooting';
    const C_TURQUOISE = 'Turquoise';
    const C_TURQUOISE_SHOOTING = 'TurquoiseShooting';
    const C_YELLOW = 'Yellow';
    const C_YELLOW_SHOOTING = 'YellowShooting';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
