<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class HandlingNameCodeType extends Enum 
{
    const C_COMBINED_HANDLING_FEE = 'CombinedHandlingFee';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_EACH_ADDITIONAL_AMOUNT = 'EachAdditionalAmount';
    const C_EACH_ADDITIONAL_AMOUNT_OFF = 'EachAdditionalAmountOff';
    const C_EACH_ADDITIONAL_PERCENT_OFF = 'EachAdditionalPercentOff';
    const C_INDIVIDUAL_HANDLING_FEE = 'IndividualHandlingFee';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
