<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class HitCounterCodeType extends Enum 
{
    const C_BASIC_STYLE = 'BasicStyle';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_GREEN_LED = 'GreenLED';
    const C_HIDDEN = 'Hidden';
    const C_HIDDEN_STYLE = 'HiddenStyle';
    const C_HONESTY_STYLE = 'HonestyStyle';
    const C_NO_HIT_COUNTER = 'NoHitCounter';
    const C_RETRO_STYLE = 'RetroStyle';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
