<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ItemTypeCodeType extends Enum 
{
    const C_ALL_ITEMS = 'AllItems';
    const C_AUCTION_ITEMS_ONLY = 'AuctionItemsOnly';
    const C_CLASSIFIED_ITEMS_ONLY = 'ClassifiedItemsOnly';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_FIXED_PRICED_ITEM = 'FixedPricedItem';
    const C_STORE_INVENTORY_ONLY = 'StoreInventoryOnly';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
