<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ItemSortTypeCodeType extends Enum 
{
    const C_BEST_OFFER = 'BestOffer';
    const C_BEST_OFFER_COUNT = 'BestOfferCount';
    const C_BEST_OFFER_COUNT_DESCENDING = 'BestOfferCountDescending';
    const C_BEST_OFFER_DESCENDING = 'BestOfferDescending';
    const C_BID_COUNT = 'BidCount';
    const C_BID_COUNT_DESCENDING = 'BidCountDescending';
    const C_BIDDER_COUNT = 'BidderCount';
    const C_BIDDER_COUNT_DESCENDING = 'BidderCountDescending';
    const C_BUYER_EMAIL = 'BuyerEmail';
    const C_BUYER_EMAIL_DESCENDING = 'BuyerEmailDescending';
    const C_BUYER_POSTAL_CODE = 'BuyerPostalCode';
    const C_BUYER_POSTAL_CODE_DESCENDING = 'BuyerPostalCodeDescending';
    const C_BUYER_USER_ID = 'BuyerUserID';
    const C_BUYER_USER_ID_DESCENDING = 'BuyerUserIDDescending';
    const C_CURRENT_PRICE = 'CurrentPrice';
    const C_CURRENT_PRICE_DESCENDING = 'CurrentPriceDescending';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_END_TIME = 'EndTime';
    const C_END_TIME_DESCENDING = 'EndTimeDescending';
    const C_FEEDBACK_LEFT = 'FeedbackLeft';
    const C_FEEDBACK_LEFT_DESCENDING = 'FeedbackLeftDescending';
    const C_FEEDBACK_RECEIVED = 'FeedbackReceived';
    const C_FEEDBACK_RECEIVED_DESCENDING = 'FeedbackReceivedDescending';
    const C_HIGH_BIDDER_USER_ID = 'HighBidderUserID';
    const C_HIGH_BIDDER_USER_ID_DESCENDING = 'HighBidderUserIDDescending';
    const C_ITEM_ID = 'ItemID';
    const C_ITEM_ID_DESCENDING = 'ItemIDDescending';
    const C_LEAD_COUNT = 'LeadCount';
    const C_LEAD_COUNT_DESCENDING = 'LeadCountDescending';
    const C_LISTING_DURATION = 'ListingDuration';
    const C_LISTING_DURATION_DESCENDING = 'ListingDurationDescending';
    const C_LISTING_TYPE = 'ListingType';
    const C_LISTING_TYPE_DESCENDING = 'ListingTypeDescending';
    const C_MAX_BID = 'MaxBid';
    const C_MAX_BID_DESCENDING = 'MaxBidDescending';
    const C_NEW_LEAD_COUNT = 'NewLeadCount';
    const C_NEW_LEAD_COUNT_DESCENDING = 'NewLeadCountDescending';
    const C_PRICE = 'Price';
    const C_PRICE_DESCENDING = 'PriceDescending';
    const C_QUANTITY = 'Quantity';
    const C_QUANTITY_AVAILABLE = 'QuantityAvailable';
    const C_QUANTITY_AVAILABLE_DESCENDING = 'QuantityAvailableDescending';
    const C_QUANTITY_DESCENDING = 'QuantityDescending';
    const C_QUANTITY_PURCHASED = 'QuantityPurchased';
    const C_QUANTITY_PURCHASED_DESCENDING = 'QuantityPurchasedDescending';
    const C_QUANTITY_SOLD = 'QuantitySold';
    const C_QUANTITY_SOLD_DESCENDING = 'QuantitySoldDescending';
    const C_QUESTION_COUNT = 'QuestionCount';
    const C_QUESTION_COUNT_DESCENDING = 'QuestionCountDescending';
    const C_RESERVE_PRICE = 'ReservePrice';
    const C_RESERVE_PRICE_DESCENDING = 'ReservePriceDescending';
    const C_SELLER_EMAIL = 'SellerEmail';
    const C_SELLER_EMAIL_DESCENDING = 'SellerEmailDescending';
    const C_SELLER_USER_ID = 'SellerUserID';
    const C_SELLER_USER_ID_DESCENDING = 'SellerUserIDDescending';
    const C_SHIPPING_SERVICE_COST = 'ShippingServiceCost';
    const C_SHIPPING_SERVICE_COST_DESCENDING = 'ShippingServiceCostDescending';
    const C_START_PRICE = 'StartPrice';
    const C_START_PRICE_DESCENDING = 'StartPriceDescending';
    const C_START_TIME = 'StartTime';
    const C_START_TIME_DESCENDING = 'StartTimeDescending';
    const C_TIME_LEFT = 'TimeLeft';
    const C_TIME_LEFT_DESCENDING = 'TimeLeftDescending';
    const C_TITLE = 'Title';
    const C_TITLE_DESCENDING = 'TitleDescending';
    const C_TOTAL_PRICE = 'TotalPrice';
    const C_TOTAL_PRICE_DESCENDING = 'TotalPriceDescending';
    const C_USER_ID = 'UserID';
    const C_USER_ID_DESCENDING = 'UserIDDescending';
    const C_WATCH_COUNT = 'WatchCount';
    const C_WATCH_COUNT_DESCENDING = 'WatchCountDescending';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
