<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class MessageTypeCodeType extends Enum 
{
    const C_ALL = 'All';
    const C_ASK_SELLER_QUESTION = 'AskSellerQuestion';
    const C_CLASSIFIEDS_BEST_OFFER = 'ClassifiedsBestOffer';
    const C_CLASSIFIEDS_CONTACT_SELLER = 'ClassifiedsContactSeller';
    const C_CONTACT_EBAY_MEMBER = 'ContactEbayMember';
    const C_CONTACT_EBAY_MEMBER_VIA_ANONYMOUS_EMAIL = 'ContacteBayMemberViaAnonymousEmail';
    const C_CONTACT_EBAY_MEMBER_VIA_COMMUNITY_LINK = 'ContacteBayMemberViaCommunityLink';
    const C_CONTACT_MY_BIDDER = 'ContactMyBidder';
    const C_CONTACT_TRANSACTION_PARTNER = 'ContactTransactionPartner';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_RESPONSE_TO_ASQ_QUESTION = 'ResponseToASQQuestion';
    const C_RESPONSE_TO_CONTACT_EBAY_MEMBER = 'ResponseToContacteBayMember';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
