<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class NotificationEventStateCodeType extends Enum 
{
    const C_CANCELED = 'Canceled';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DELIVERED = 'Delivered';
    const C_FAILED = 'Failed';
    const C_FAILED_PENDING = 'FailedPending';
    const C_MARKED_DOWN = 'MarkedDown';
    const C_MARKED_DOWN_PENDING = 'MarkedDownPending';
    const C_NEW = 'New';
    const C_PENDING = 'Pending';
    const C_REJECTED = 'Rejected';
    const C_UNDELIVERABLE = 'Undeliverable';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
