<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PaidStatusCodeType extends Enum 
{
    const C_BUYER_HAS_NOT_COMPLETED_CHECKOUT = 'BuyerHasNotCompletedCheckout';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_MARKED_AS_PAID = 'MarkedAsPaid';
    const C_NOT_PAID = 'NotPaid';
    const C_PAID = 'Paid';
    const C_PAID_COD = 'PaidCOD';
    const C_PAID_WITH_PAISA_PAY_ESCROW = 'PaidWithPaisaPayEscrow';
    const C_PAID_WITH_PAY_PAL = 'PaidWithPayPal';
    const C_PAYMENT_PENDING = 'PaymentPending';
    const C_PAYMENT_PENDING_WITH_PAISA_PAY_ESCROW = 'PaymentPendingWithPaisaPayEscrow';
    const C_PAYMENT_PENDING_WITH_PAY_PAL = 'PaymentPendingWithPayPal';
    const C_PAY_UPON_INVOICE = 'PayUponInvoice';
    const C_REFUNDED = 'Refunded';
    const C_WAITING_FOR_COD_PAYMENT = 'WaitingForCODPayment';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
