<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PaymentHoldReasonCodeType extends Enum 
{
    const C_BELOW_STANDARD_SELLER = 'BelowStandardSeller';
    const C_CASUAL_SELLER = 'CasualSeller';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_EBP_CASE_OPEN = 'EbpCaseOpen';
    const C_NEW_PAYPAL_ACCOUNT_ADDED = 'NewPaypalAccountAdded';
    const C_NEW_SELLER = 'NewSeller';
    const C_NOT_AVAILABLE = 'NotAvailable';
    const C_OTHER = 'Other';
    const C_REINSTATEMENT_AFTER_SUSPENSION = 'ReinstatementAfterSuspension';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
