<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PayPalAccountLevelCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_INTERNATIONAL_UNVERIFIED = 'InternationalUnverified';
    const C_INTERNATIONAL_VERIFIED = 'InternationalVerified';
    const C_INVALID = 'Invalid';
    const C_TRUSTED = 'Trusted';
    const C_UNKNOWN = 'Unknown';
    const C_UNVERIFIED = 'Unverified';
    const C_VERIFIED = 'Verified';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
