<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PeriodCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DAYS_180 = 'Days_180';
    const C_DAYS_30 = 'Days_30';
    const C_DAYS_360 = 'Days_360';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
