<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class RequiredSellerActionCodeType extends Enum 
{
    const C_CONTACT_EBAY_CS = 'ContacteBayCS';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_MARK_AS_SHIPPED = 'MarkAsShipped';
    const C_RESOLVE_BUYER_MESSAGE_INR = 'ResolveBuyerMessageInr';
    const C_RESOLVE_BUYER_MESSAGE_SNAD = 'ResolveBuyerMessageSnad';
    const C_RESOLVEE_BP_CASE = 'ResolveeBPCase';
    const C_RESOLVE_PPP_ICASE = 'ResolvePPPIcase';
    const C_RESOLVE_RETURN = 'ResolveReturn';
    const C_UPLOAD_TRACKING_INFO = 'UploadTrackingInfo';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
