<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerSoldListingsSortTypeCodeType extends Enum 
{
    const C_BUYER_EMAIL = 'BuyerEmail';
    const C_BUYER_POSTAL_CODE = 'BuyerPostalCode';
    const C_CHECKOUT_STATE = 'CheckoutState';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_CUSTOM_LABEL = 'CustomLabel';
    const C_DAYS_SINCE_SALE = 'DaysSinceSale';
    const C_EMAILS_SENT = 'EmailsSent';
    const C_FEEDBACK_LEFT = 'FeedbackLeft';
    const C_FEEDBACK_RECEIVED = 'FeedbackReceived';
    const C_LISTED_ON = 'ListedOn';
    const C_PAID_DATE = 'PaidDate';
    const C_PAID_STATE = 'PaidState';
    const C_RESERVE_PRICE = 'ReservePrice';
    const C_SALE_DATE = 'SaleDate';
    const C_SALE_FORMAT = 'SaleFormat';
    const C_SALES_RECORD_ID = 'SalesRecordID';
    const C_SHIPPED_DATE = 'ShippedDate';
    const C_SHIPPED_STATE = 'ShippedState';
    const C_SHIPPING_COST = 'ShippingCost';
    const C_SOLD_ON = 'SoldOn';
    const C_START_PRICE = 'StartPrice';
    const C_TOTAL_PRICE = 'TotalPrice';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
