<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellerPaymentMethodCodeType extends Enum 
{
    const C_CREDIT_CARD = 'CreditCard';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DIRECT_DEBIT = 'DirectDebit';
    const C_DIRECT_DEBIT_PENDING_SIGNATURE_MANDATE = 'DirectDebitPendingSignatureMandate';
    const C_DIRECT_DEBIT_PENDING_VERIFICATION = 'DirectDebitPendingVerification';
    const C_EBAY_DIRECT_PAY = 'eBayDirectPay';
    const C_NOTHING_ON_FILE = 'NothingOnFile';
    const C_PAY_PAL = 'PayPal';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
