<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerPaisaPayPropertyTypeCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_PAISA_PAY_AWAITING_SHIPMENT = 'PaisaPayAwaitingShipment';
    const C_PAISA_PAY_PENDING_RECEIVED = 'PaisaPayPendingReceived';
    const C_PAISA_PAY_REFUND_INITIATED = 'PaisaPayRefundInitiated';
    const C_PAISA_PAY_TIME_EXTENSION_REQUEST_DECLINED = 'PaisaPayTimeExtensionRequestDeclined';
    const C_PAISA_PAY_TIME_EXTENSION_REQUESTED = 'PaisaPayTimeExtensionRequested';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
