<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerInventoryPropertyTypeCodeType extends Enum 
{
    const C_ACTIVE = 'Active';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_IN_ACTIVE = 'InActive';
    const C_LOW_STOCK = 'LowStock';
    const C_PRODUCTS_OUT_OF_STOCK = 'ProductsOutOfStock';
    const C_WITH_LISTINGS = 'WithListings';
    const C_WITHOUT_LISTINGS = 'WithoutListings';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
