<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerAutoRelistTypeCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_RELIST_CONTINUOUSLY = 'RelistContinuously';
    const C_RELIST_CONTINUOUSLY_UNTIL_SOLD = 'RelistContinuouslyUntilSold';
    const C_RELIST_ONCE_IF_NOT_SOLD = 'RelistOnceIfNotSold';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
