<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerSearchTypeCodeType extends Enum 
{
    const C_BUYER_EMAIL = 'BuyerEmail';
    const C_BUYER_FULL_NAME = 'BuyerFullName';
    const C_BUYER_USER_ID = 'BuyerUserID';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_CUSTOM_LABEL = 'CustomLabel';
    const C_ITEM_ID = 'ItemID';
    const C_PRODUCT_ID = 'ProductID';
    const C_PRODUCT_NAME = 'ProductName';
    const C_SALE_RECORD_ID = 'SaleRecordID';
    const C_TITLE = 'Title';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
