<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ShippingRegionCodeType extends Enum 
{
    const C_AFRICA = 'Africa';
    const C_AMERICAS = 'Americas';
    const C_ASIA = 'Asia';
    const C_CARIBBEAN = 'Caribbean';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_EUROPE = 'Europe';
    const C_EUROPEAN_UNION = 'EuropeanUnion';
    const C_LATIN_AMERICA = 'LatinAmerica';
    const C_MIDDLE_EAST = 'MiddleEast';
    const C_NONE = 'None';
    const C_NORTH_AMERICA = 'NorthAmerica';
    const C_OCEANIA = 'Oceania';
    const C_SOUTH_AMERICA = 'SouthAmerica';
    const C_WILL_NOT_SHIP = 'WillNotShip';
    const C_WORLDWIDE = 'Worldwide';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
