<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ShippingRateTypeCodeType extends Enum 
{
    const C_COMMERCIAL_PLUS = 'CommercialPlus';
    const C_COUNTER = 'Counter';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DAILY_PICKUP = 'DailyPickup';
    const C_DISCOUNTED = 'Discounted';
    const C_GOLD_SILVER = 'GoldSilver';
    const C_ON_DEMAND = 'OnDemand';
    const C_PLAT_TITANIUM = 'PlatTitanium';
    const C_STANDARD_LIST = 'StandardList';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
