<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SimpleItemSortCodeType extends Enum 
{
    const C_BEST_MATCH = 'BestMatch';
    const C_BEST_MATCH_CATEGORY_GROUP = 'BestMatchCategoryGroup';
    const C_BID_COUNT = 'BidCount';
    const C_COUNTRY = 'Country';
    const C_CURRENT_BID = 'CurrentBid';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DISTANCE = 'Distance';
    const C_END_TIME = 'EndTime';
    const C_PRICE_PLUS_SHIPPING = 'PricePlusShipping';
    const C_START_DATE = 'StartDate';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
