<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SiteCodeType extends Enum 
{
    const C_AUSTRALIA = 'Australia';
    const C_AUSTRIA = 'Austria';
    const C_BELGIUM_DUTCH = 'Belgium_Dutch';
    const C_BELGIUM_FRENCH = 'Belgium_French';
    const C_CANADA = 'Canada';
    const C_CANADA_FRENCH = 'CanadaFrench';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_EBAY_MOTORS = 'eBayMotors';
    const C_FRANCE = 'France';
    const C_GERMANY = 'Germany';
    const C_HONG_KONG = 'HongKong';
    const C_INDIA = 'India';
    const C_IRELAND = 'Ireland';
    const C_ITALY = 'Italy';
    const C_MALAYSIA = 'Malaysia';
    const C_NETHERLANDS = 'Netherlands';
    const C_PHILIPPINES = 'Philippines';
    const C_POLAND = 'Poland';
    const C_RUSSIA = 'Russia';
    const C_SINGAPORE = 'Singapore';
    const C_SPAIN = 'Spain';
    const C_SWITZERLAND = 'Switzerland';
    const C_UK = 'UK';
    const C_US = 'US';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
