<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class StoreSubscriptionLevelCodeType extends Enum 
{
    const C_ANCHOR = 'Anchor';
    const C_BASIC = 'Basic';
    const C_CLOSE = 'Close';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_ENTERPRISE = 'Enterprise';
    const C_FEATURED = 'Featured';
    const C_STARTER = 'Starter';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
