<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class StoreItemListSortOrderCodeType extends Enum 
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_ENDING_FIRST = 'EndingFirst';
    const C_HIGHEST_PRICED = 'HighestPriced';
    const C_HIGHEST_PRICED_PLUS_SHIPPING = 'HighestPricedPlusShipping';
    const C_LOWEST_PRICED = 'LowestPriced';
    const C_LOWEST_PRICED_PLUS_SHIPPING = 'LowestPricedPlusShipping';
    const C_NEWLY_LISTED = 'NewlyListed';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
