<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SummaryWindowPeriodCodeType extends Enum 
{
    const C_CURRENT_MONTH = 'CurrentMonth';
    const C_CURRENT_WEEK = 'CurrentWeek';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_LAST24_HOURS = 'Last24Hours';
    const C_LAST31_DAYS = 'Last31Days';
    const C_LAST60_DAYS = 'Last60Days';
    const C_LAST7_DAYS = 'Last7Days';
    const C_LAST_MONTH = 'LastMonth';
    const C_LAST_WEEK = 'LastWeek';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
