<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class UserStatusCodeType extends Enum 
{
    const C_ACCOUNT_ON_HOLD = 'AccountOnHold';
    const C_CONFIRMED = 'Confirmed';
    const C_CREDIT_CARD_VERIFY = 'CreditCardVerify';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DELETED = 'Deleted';
    const C_GHOST = 'Ghost';
    const C_GUEST = 'Guest';
    const C_IN_MAINTENANCE = 'InMaintenance';
    const C_MERGED = 'Merged';
    const C_REGISTRATION_CODE_MAIL_OUT = 'RegistrationCodeMailOut';
    const C_SUSPENDED = 'Suspended';
    const C_TERM_PENDING = 'TermPending';
    const C_UNCONFIRMED = 'Unconfirmed';
    const C_UNKNOWN = 'Unknown';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
