<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ValueTypeCodeType extends Enum 
{
    const C_CEDULA = 'CEDULA';
    const C_CNPJ = 'CNPJ';
    const C_CODICE_FISCALE = 'CodiceFiscale';
    const C_CPF_TAX_ID = 'CPFTaxID';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DATE = 'Date';
    const C_DECIMAL = 'Decimal';
    const C_DNI = 'DNI';
    const C_DRIVER_LICENSE = 'DriverLicense';
    const C_EAN = 'EAN';
    const C_ISBN = 'ISBN';
    const C_NIE = 'NIE';
    const C_NIF = 'NIF';
    const C_NIT = 'NIT';
    const C_NUMERIC = 'Numeric';
    const C_RUSSIAN_PASSPORT = 'RussianPassport';
    const C_TEXT = 'Text';
    const C_TURKEY_ID = 'TurkeyID';
    const C_UPC = 'UPC';

    /**
     * Just for test case,because when called outside class, get_parent_class() always return false,unless the function
     * and class is in the same file
     *
     * @return string
     */
    public static function getParentClass()
    {
        return get_parent_class();
    }

}
